version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Canada/Central
  open-pull-requests-limit: 10
  reviewers:
  - ThePuzzlemaker
  labels:
  - A-deps
  - B-untested
  - S-awaiting-review
